---
title: Siteleaf Test Site
timezone: UTC
collections:
  blue:
    title: Blue
    output: true
  posts:
    title: Posts
    output: true
  red:
    title: Red
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: 'A test site for the Siteleaf CMS.

'
baseurl: "/jekyll-siteleaf"
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
